# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d32337a92b9450eada3366820b0762db293a56dbc485d305ccdc4cf5a15b5171624de9a0dd2a4a09d3636e728ff7cdafad8e529cec76f0478433ddb05d402434

test:
  secret_key_base: 2be206ad7eae80b7e4a34791dd3112d83c74bf9b1c25a718fce103e327e1bb88ebf1e7e2a27182beba1176f33af1669ca17c3528699d254afeaeb64a626b3ed2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
